name:                my-tiger
version:             0.1.0.0
github:              "3to5thpower/my-tiger"
license:             MIT
author:              "Genki Nishimi"
maintainer:          "nisi3genki@gmail.com"
copyright:           "2021 Genki Nishimi"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/my-tiger#readme>

dependencies:
- base >= 4.7 && < 5
- array

library:
  source-dirs: src

executables:
  my-tiger-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - my-tiger

tests:
  my-tiger-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - my-tiger
